version: "3"

services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      #PGUSER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 5

  redishost:
    image: redis:7
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    # environment:
    #  REDIS_HOST: queque
    #  REDIS_PORT: 6379
    #  REDIS_PASSWORD: sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
    expose:
      - 8081
    environment:
      PGDB: "${POSTGRES_DB}"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
    command: bash -c "
      export DJANGO_SETTINGS_MODULE=settings.prod_settings
      && python manage.py migrate 
      && (python manage.py rqworker &)
      && (celery -A settings worker &)
      && python manage.py fill_db 
      && gunicorn settings.wsgi -b 0.0.0.0:8081
      "
      # python manage.py sendtestemail mistrikov@mail.ru
      # gunicorn settings.wsgi -b 0.0.0.0:8081
      # python manage.py runserver 0.0.0.0:8081
      # && (celery --app settings worker &)
    depends_on:
      pg:
        condition: service_healthy
  
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - backend

